name: Terraform Deploy

on:
  workflow_dispatch: # Allows you to manually trigger the workflow
#  push:
#    branches:
#      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws

    # Define environment variables at the job level
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: terraform apply --auto-approve

      # Step to upload the state file as an artifact
    - name: Upload Terraform state
      uses: actions/upload-artifact@v3
      with:
        name: tfstate
        path: .terraform/terraform.tfstate

#    - name: Clean up
#      run: rm tfplan