name: Terraform Deploy

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws

    # Define environment variables at the job level
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: terraform apply --auto-approve

#    - name: Upload Terraform state to S3
#      run: aws s3 cp .terraform/terraform.tfstate s3://your-s3-bucket-name/path/to/terraform.tfstate

    - name: Clean up
      run: rm tfplan