name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws

    # Define environment variables at the job level
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: terraform apply --auto-approve

    - name: Clean up
      run: rm tfplan

  # Add a new job for destroying resources (Optional)
  destroy:
    runs-on: ubuntu-latest
    environment: aws
    needs: terraform  # Ensure this job runs after the apply job
    if: ${{ github.event_name == 'workflow_dispatch' }} # Only run when triggered manually

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 2: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 3: Destroy Terraform resources
      - name: Destroy Terraform resources
        run: terraform destroy

      # Step 4: Clean up (Optional)
      - name: Clean up
        run: rm -rf .terraform
